### PR TITLE
Del localhost

### PR DESCRIPTION
**Pull request by thomasbnt**
Not cool for people who develop in localhost 😶

### CODE REVIEW

**Comment by msva** [comment]
there is also localhost in second half of the file: https://github.com/userstyles-world/tweaks/blob/main/tweaks.user.styl#L139

**Comment by thomasbnt** [comment]
Seems useless to create a PR.

**Comment by vednoc** [comment]
Hey @thomasbnt and @msva, I sincerely apologize for not seeing this PR earlier. I struggle a lot with notifications, so the best way to contact me is by pinging me directly. I'll really try to do better in the future.

**Comment by thomasbnt** [comment]
Thanks!

**Pull request merged**
